package net.opentsdb.catalog.hibernate;

// Generated Nov 5, 2013 11:47:56 AM by Hibernate Tools 4.0.0

/**
 * TsdFqnTagpair generated by hbm2java
 */
public class TsdFqnTagpair implements java.io.Serializable {

	private Long fqnTpId;
	private TsdTagpair tsdTagpair;
	private TsdFqn tsdFqn;
	private byte porder;

	public TsdFqnTagpair() {
	}

	public TsdFqnTagpair(TsdTagpair tsdTagpair, TsdFqn tsdFqn, byte porder) {
		this.tsdTagpair = tsdTagpair;
		this.tsdFqn = tsdFqn;
		this.porder = porder;
	}

	public Long getFqnTpId() {
		return this.fqnTpId;
	}

	public void setFqnTpId(Long fqnTpId) {
		this.fqnTpId = fqnTpId;
	}

	public TsdTagpair getTsdTagpair() {
		return this.tsdTagpair;
	}

	public void setTsdTagpair(TsdTagpair tsdTagpair) {
		this.tsdTagpair = tsdTagpair;
	}

	public TsdFqn getTsdFqn() {
		return this.tsdFqn;
	}

	public void setTsdFqn(TsdFqn tsdFqn) {
		this.tsdFqn = tsdFqn;
	}

	public byte getPorder() {
		return this.porder;
	}

	public void setPorder(byte porder) {
		this.porder = porder;
	}

}
