package net.opentsdb.catalog.hibernate;

// Generated Nov 5, 2013 11:47:56 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TsdFqn generated by hbm2java
 */
public class TsdFqn implements java.io.Serializable {

	private Long fqnid;
	private TsdMetric tsdMetric;
	private String fqn;
	private String tsuid;
	private Set<TsdFqnTagpair> tsdFqnTagpairs = new HashSet<TsdFqnTagpair>(0);

	public TsdFqn() {
	}

	public TsdFqn(TsdMetric tsdMetric, String fqn, String tsuid) {
		this.tsdMetric = tsdMetric;
		this.fqn = fqn;
		this.tsuid = tsuid;
	}

	public TsdFqn(TsdMetric tsdMetric, String fqn, String tsuid,
			Set<TsdFqnTagpair> tsdFqnTagpairs) {
		this.tsdMetric = tsdMetric;
		this.fqn = fqn;
		this.tsuid = tsuid;
		this.tsdFqnTagpairs = tsdFqnTagpairs;
	}

	public Long getFqnid() {
		return this.fqnid;
	}

	public void setFqnid(Long fqnid) {
		this.fqnid = fqnid;
	}

	public TsdMetric getTsdMetric() {
		return this.tsdMetric;
	}

	public void setTsdMetric(TsdMetric tsdMetric) {
		this.tsdMetric = tsdMetric;
	}

	public String getFqn() {
		return this.fqn;
	}

	public void setFqn(String fqn) {
		this.fqn = fqn;
	}

	public String getTsuid() {
		return this.tsuid;
	}

	public void setTsuid(String tsuid) {
		this.tsuid = tsuid;
	}

	public Set<TsdFqnTagpair> getTsdFqnTagpairs() {
		return this.tsdFqnTagpairs;
	}

	public void setTsdFqnTagpairs(Set<TsdFqnTagpair> tsdFqnTagpairs) {
		this.tsdFqnTagpairs = tsdFqnTagpairs;
	}

}
