package net.opentsdb.catalog.hibernate;

// Generated Nov 5, 2013 11:47:56 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TsdMetric generated by hbm2java
 */
public class TsdMetric implements java.io.Serializable {

	private String uid;
	private String name;
	private Date created;
	private String description;
	private String displayName;
	private String notes;
	private String custom;
	private Set<TsdFqn> tsdFqns = new HashSet<TsdFqn>(0);

	public TsdMetric() {
	}

	public TsdMetric(String uid, String name, Date created) {
		this.uid = uid;
		this.name = name;
		this.created = created;
	}

	public TsdMetric(String uid, String name, Date created, String description,
			String displayName, String notes, String custom, Set<TsdFqn> tsdFqns) {
		this.uid = uid;
		this.name = name;
		this.created = created;
		this.description = description;
		this.displayName = displayName;
		this.notes = notes;
		this.custom = custom;
		this.tsdFqns = tsdFqns;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getCustom() {
		return this.custom;
	}

	public void setCustom(String custom) {
		this.custom = custom;
	}

	public Set<TsdFqn> getTsdFqns() {
		return this.tsdFqns;
	}

	public void setTsdFqns(Set<TsdFqn> tsdFqns) {
		this.tsdFqns = tsdFqns;
	}

}
