package net.opentsdb.catalog.hibernate;

// Generated Nov 5, 2013 11:47:56 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TsdTagpair generated by hbm2java
 */
public class TsdTagpair implements java.io.Serializable {

	private String uid;
	private TsdTagk tsdTagk;
	private TsdTagv tsdTagv;
	private String name;
	private Set<TsdFqnTagpair> tsdFqnTagpairs = new HashSet<TsdFqnTagpair>(0);

	public TsdTagpair() {
	}

	public TsdTagpair(String uid, TsdTagk tsdTagk, TsdTagv tsdTagv, String name) {
		this.uid = uid;
		this.tsdTagk = tsdTagk;
		this.tsdTagv = tsdTagv;
		this.name = name;
	}

	public TsdTagpair(String uid, TsdTagk tsdTagk, TsdTagv tsdTagv,
			String name, Set<TsdFqnTagpair> tsdFqnTagpairs) {
		this.uid = uid;
		this.tsdTagk = tsdTagk;
		this.tsdTagv = tsdTagv;
		this.name = name;
		this.tsdFqnTagpairs = tsdFqnTagpairs;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public TsdTagk getTsdTagk() {
		return this.tsdTagk;
	}

	public void setTsdTagk(TsdTagk tsdTagk) {
		this.tsdTagk = tsdTagk;
	}

	public TsdTagv getTsdTagv() {
		return this.tsdTagv;
	}

	public void setTsdTagv(TsdTagv tsdTagv) {
		this.tsdTagv = tsdTagv;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<TsdFqnTagpair> getTsdFqnTagpairs() {
		return this.tsdFqnTagpairs;
	}

	public void setTsdFqnTagpairs(Set<TsdFqnTagpair> tsdFqnTagpairs) {
		this.tsdFqnTagpairs = tsdFqnTagpairs;
	}

}
