-- ====================================================================
-- tsdb-sqlcatalog DDL
-- Whitehead, 2013
-- 
-- ====================================================================


CREATE TABLE IF NOT EXISTS TSD_TAGK (
    UID CHAR(6) NOT NULL ,
    NAME VARCHAR2(60) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(120),
    DISPLAY_NAME VARCHAR2(60),
    NOTES VARCHAR2(120),
    CUSTOM VARCHAR2(120)    
);

CREATE UNIQUE INDEX IF NOT EXISTS TSD_TAGK_AK ON TSD_TAGK (NAME ASC);
ALTER TABLE TSD_TAGK ADD CONSTRAINT IF NOT EXISTS TSD_TAGK_PK PRIMARY KEY ( UID ) ;

CREATE TABLE IF NOT EXISTS TSD_TAGV (
    UID CHAR(6) NOT NULL ,
    NAME VARCHAR2(60) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(120),
    DISPLAY_NAME VARCHAR2(60),
    NOTES VARCHAR2(120),
    CUSTOM VARCHAR2(120)    
);

CREATE UNIQUE INDEX IF NOT EXISTS TSD_TAGV_AK ON TSD_TAGV (NAME ASC);
ALTER TABLE TSD_TAGV ADD CONSTRAINT IF NOT EXISTS TSD_TAGV_PK PRIMARY KEY ( UID ) ;

CREATE TABLE IF NOT EXISTS TSD_METRIC (
    UID CHAR(6) NOT NULL ,
    NAME VARCHAR2(60) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(120),
    DISPLAY_NAME VARCHAR2(60),
    NOTES VARCHAR2(120),
    CUSTOM VARCHAR2(120)    
);

CREATE UNIQUE INDEX IF NOT EXISTS TSD_METRIC_AK ON TSD_METRIC (NAME ASC);
ALTER TABLE TSD_METRIC ADD CONSTRAINT IF NOT EXISTS TSD_METRIC_PK PRIMARY KEY ( UID ) ;


CREATE TABLE IF NOT EXISTS TSD_TAGPAIR (
	UID CHAR(12) NOT NULL,
	TAGK CHAR(6) NOT NULL REFERENCES TSD_TAGK(UID),
	TAGV CHAR(6) NOT NULL REFERENCES TSD_TAGV(UID),
	NAME  VARCHAR2(120) NOT NULL
);


CREATE UNIQUE INDEX IF NOT EXISTS TSD_TAGPAIR_AK ON TSD_TAGPAIR (TAGK ASC, TAGV ASC);
CREATE INDEX IF NOT EXISTS TSD_TAGPAIR_K_IDX ON TSD_TAGPAIR (TAGK ASC);
CREATE INDEX IF NOT EXISTS TSD_TAGPAIR_V_IDX ON TSD_TAGPAIR (TAGV ASC);
CREATE INDEX IF NOT EXISTS TSD_TAGPAIR_NAME_IDX ON TSD_TAGPAIR (NAME ASC);
ALTER TABLE TSD_TAGPAIR ADD CONSTRAINT IF NOT EXISTS TSD_TAGPAIR_PK PRIMARY KEY ( UID ) ;

CREATE TABLE IF NOT EXISTS TSD_FQN_TAGPAIR (
	FQN_TP_ID BIGINT NOT NULL IDENTITY,
	FQNID BIGINT NOT NULL,
	UID CHAR(12) NOT NULL,
	PORDER TINYINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS TSD_FQN_TAGPAIR_AK ON TSD_FQN_TAGPAIR (FQN_TP_ID);
CREATE UNIQUE INDEX IF NOT EXISTS TSD_FQN_TAGPAIR_IND ON TSD_FQN_TAGPAIR (FQNID, UID, PORDER);
ALTER TABLE TSD_FQN_TAGPAIR ADD CONSTRAINT IF NOT EXISTS TSD_FQN_TAGPAIR_FK FOREIGN KEY(UID) REFERENCES TSD_TAGPAIR ( UID );

CREATE TABLE IF NOT EXISTS TSD_FQN (
	FQNID BIGINT NOT NULL IDENTITY,
	METRIC_UID CHAR(6) NOT NULL,
	FQN VARCHAR(4000) NOT NULL,
	TSUID VARCHAR(120) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS TSD_FQN_AK ON TSD_FQN (FQNID);
CREATE UNIQUE INDEX IF NOT EXISTS TSD_FQN_TSUID_AK ON TSD_FQN (TSUID);
CREATE UNIQUE INDEX IF NOT EXISTS TSD_FQN_FQN_AK ON TSD_FQN (FQN);
--ALTER TABLE TSD_FQN ADD CONSTRAINT IF NOT EXISTS TSD_FQN_TAGPAIR_FK_FQNID FOREIGN KEY(FQNID) REFERENCES TSD_FQN_TAGPAIR ( FQNID );
ALTER TABLE TSD_FQN_TAGPAIR ADD CONSTRAINT IF NOT EXISTS TSD_FQN_TAGPAIR_FQNID_FK FOREIGN KEY(FQNID) REFERENCES TSD_FQN ( FQNID );
ALTER TABLE TSD_FQN ADD CONSTRAINT IF NOT EXISTS TSD_FQN_METRIC_FK FOREIGN KEY(METRIC_UID) REFERENCES TSD_METRIC ( UID );

-- ==============================================================================================
--  User Defined Functions
-- ==============================================================================================


CREATE ALIAS IF NOT EXISTS TAGVNAME FOR "net.opentsdb.catalog.h2.H2Support.tagvName";
CREATE ALIAS IF NOT EXISTS TAGKNAME FOR "net.opentsdb.catalog.h2.H2Support.tagkName";
CREATE ALIAS IF NOT EXISTS METRICNAME FOR "net.opentsdb.catalog.h2.H2Support.metricName";

CREATE ALIAS IF NOT EXISTS TAGVUID FOR "net.opentsdb.catalog.h2.H2Support.tagvUid";
CREATE ALIAS IF NOT EXISTS TAGKUID FOR "net.opentsdb.catalog.h2.H2Support.tagkUid";
CREATE ALIAS IF NOT EXISTS METRICUID FOR "net.opentsdb.catalog.h2.H2Support.metricUid";

CREATE ALIAS IF NOT EXISTS TAGPAIRN FOR "net.opentsdb.catalog.h2.H2Support.tagPairUidByName";
CREATE ALIAS IF NOT EXISTS TAGPAIRU FOR "net.opentsdb.catalog.h2.H2Support.tagPairUidByNames";

CREATE ALIAS IF NOT EXISTS TAGPAIRKEY FOR "net.opentsdb.catalog.h2.H2Support.tagPairKeyNameByUid";
CREATE ALIAS IF NOT EXISTS TAGPAIRVALUE FOR "net.opentsdb.catalog.h2.H2Support.tagPairValueNameByUid";



