-- ====================================================================
-- tsdb-sqlcatalog DDL
-- Whitehead, 2013
-- 
-- ====================================================================

CREATE TABLE IF NOT EXISTS TSD_TAGK (
    UID CHAR(6) NOT NULL ,
    NAME VARCHAR2(60) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(120),
    DISPLAY_NAME VARCHAR2(60),
    NOTES VARCHAR2(120),
    CUSTOM VARCHAR2(120)    
);

CREATE UNIQUE INDEX IF NOT EXISTS TSD_TAGK_IDX ON TSD_TAGK (NAME ASC);
ALTER TABLE TSD_TAGK ADD CONSTRAINT IF NOT EXISTS TSD_TAGK_PK PRIMARY KEY ( UID ) ;

CREATE TABLE IF NOT EXISTS TSD_TAGV (
    UID CHAR(6) NOT NULL ,
    NAME VARCHAR2(60) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(120),
    DISPLAY_NAME VARCHAR2(60),
    NOTES VARCHAR2(120),
    CUSTOM VARCHAR2(120)    
);

CREATE UNIQUE INDEX IF NOT EXISTS TSD_TAGV_IDX ON TSD_TAGV (NAME ASC);
ALTER TABLE TSD_TAGV ADD CONSTRAINT IF NOT EXISTS TSD_TAGV_PK PRIMARY KEY ( UID ) ;

CREATE TABLE IF NOT EXISTS TSD_METRIC (
    UID CHAR(6) NOT NULL ,
    NAME VARCHAR2(60) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(120),
    DISPLAY_NAME VARCHAR2(60),
    NOTES VARCHAR2(120),
    CUSTOM VARCHAR2(120)    
);

CREATE UNIQUE INDEX IF NOT EXISTS TSD_METRIC_IDX ON TSD_METRIC (NAME ASC);
ALTER TABLE TSD_METRIC ADD CONSTRAINT IF NOT EXISTS TSD_METRIC_PK PRIMARY KEY ( UID ) ;


